name: pure_music
description: pureMusic

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  audio_service: ^0.18.7
  just_audio: ^0.9.28
  rxdart: ^0.27.5
  get_it: ^7.2.0
  audioplayers: ^0.20.1
  # 事件总线
  event_bus: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audiotagger: ^2.2.1
  palette_generator: ^0.3.3+1
  cached_network_image: ^3.2.1
  on_audio_query: ^2.6.1
  url_launcher: ^6.1.5
  file_picker: ^5.0.1
  permission_handler: ^9.2.0
  #在 Android、iOS 和 macOS 中创建和提取 ZIP 存档文件。递归压缩目录或给定文件列表中的所有文件
  flutter_archive: ^4.2.2
  supabase: ^0.2.15
  device_info_plus: ^4.1.0
  material_design_icons_flutter: 5.0.5955-rc.1
  package_info_plus: ^1.4.0
  salomon_bottom_bar: ^3.3.1
  flutter_displaymode: ^0.4.0
  # 使 flutter 应用程序能够接收来自其他应用程序的共享照片、文本或 url。使 flutter 应用程序能够接收来自其他应用程序的共享照片、文本或 url
  receive_sharing_intent: ^1.4.5
  share_plus: ^4.0.10
  flip_card: ^0.6.0
  sliding_up_panel: ^2.0.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
  msix: ^3.6.3

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

msix_config:
  display_name: BlackHole
  publisher_display_name: Ankit Sangwan
  identity_name: com.shadow.blackhole
  icons_background_color: transparent
  logo_path: assets/ic_launcher.png
  file_extension: .mp3, .m4a