name: pure_music
description: A new Flutter project.

version: 0.1.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  shared_preferences: ^0.5.3+5
  # 本地json对象存储
  localstorage: ^4.0.1+2
  #状态管理
  provider: ^4.0.0
  # UI
  oktoast: ^3.1.7
  pull_to_refresh: ^2.0.0
  dio: ^5.1.1
#  device_info: ^0.4.0+1
#  package_info: ^0.4.0+6
  shimmer: ^1.0.0
  bubble_bottom_bar: ^1.2.0
  audioplayers: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cached_network_image: ^3.0.0
  http: ^0.13.5
  path_provider: ^2.0.12
  change_notifier: ^0.24.0
  timelines: ^0.1.0
  font_awesome_flutter: ^10.4.0
  # 歌词显示
  flutter_lyric: ^2.0.4+6
  # 本地存储
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  getwidget: ^2.0.4
#  audio_service: ^0.18.9
#  just_audio: ^0.9.32
#  rxdart: ^0.27.7
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/